#define USER_BUTTON       36
#define WAKE_SWITCH       39
#define SUCTION_SWITCH    34
#define JET_SWITCH        35
#define BATT_LEVEL        32
#define KNOB_PIN          32
#define PRESSURE_SENSOR   33
#define NEO_PIN           14
#define HEARTBEAT_LED     13
#define HB_LED_LEFT       23
#define SUCTION_PWM       19
#define JET_PWM           18
#define HB_LED_RIGHT       5
#define COMMS_LED         15
